name: Create VeniceRCON Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  # Creating release on GitHub
  release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
      - shell: bash
        run: |
          echo "${{ steps.create_release.outputs.upload_url }}" > url.txt
      - name: upload release url
        uses: actions/upload-artifact@v1
        with:
          name: release-info
          path: url.txt
  build-frontend:
    name: build frontend
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          repository: alliance-apps/VeniceRCON-UI
      - name: use node version 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install dependencies
        run: npm ci
      - name: build release
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: dist/
  build-backend:
    name: build backend
    runs-on: ubuntu-latest
    environment: s3release
    needs: [release, build-frontend]
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          repository: alliance-apps/VeniceRCON-backend
      - name: use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: download release url
        uses: actions/download-artifact@v1
        with:
          name: release-info
      - shell: bash
        id: release
        run: |
          RELEASE_URL=`cat release-info/url.txt`
          echo "Got URL $RELEASE_URL"
          echo "::set-output name=release_url::$RELEASE_URL"
          echo "saved output: ${{ steps.release.outputs.release_url }}"
      - name: install dependencies
        run: npm ci
      - name: build release
        run: npm run build
      - name: remove node_modules
        run: rm -R node_modules
      - name: clean and move to packing dir
        run: |
          mkdir venicercon-${{ github.event.inputs.version }}
          cp -r -t venicercon-${{ github.event.inputs.version }} public lib package*.json README.md config.default.yaml ecosystem.config.js
          find ./venicercon-${{ github.event.inputs.version }} -name "*.js.map" -type f -delete
      - name: download frontend
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: venicercon-${{ github.event.inputs.version }}/public
      - name: pack project
        run: |
          tar -czvf venicercon-${{ github.event.inputs.version }}.tar.gz venicercon-${{ github.event.inputs.version }}
          cp venicercon-${{ github.event.inputs.version }}.tar.gz venicercon-latest.tar.gz
      - name: upload release asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.release_url }}
          asset_path: ./venicercon.tar.gz
          asset_name: venicercon.tar.gz
          asset_content_type: application/tar+gzip
      - name: upload version to allianceapps s3
        shell: bash
        env:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_s3_bucket: ${{ secrets.AWS_BUCKET }}
        run: |
          sudo apt-get update && sudo apt-get -y install awscli
          aws configure set aws_access_key_id $aws_key_id
          aws configure set aws_secret_access_key $aws_secret_access_key 
          aws configure set default.region eu-west-1
          aws s3 cp venicercon-latest.tar.gz s3://$aws_s3_bucket/ --acl public-read
